name: MadSquidProductions.com
favicon: null
layout_spectrum: 0.49694
typography_spectrum: 0.28608
title: Mad Squid Productionsâ„¢
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72819193-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#1c4347'
    - '#567e82'
    - '#b38124'
  brandStrength: 0.5
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
